# Generated by Django 3.0.3 on 2020-03-27 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=55, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified on')),
                ('context', models.TextField()),
            ],
        ),
    ]
